# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0002_review_review_sentiments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_sentiments',
            field=models.TextField(),
        ),
    ]
