# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0003_auto_20181114_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='movie',
            name='review_contents',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='review_sentiments',
            field=models.TextField(default=''),
        ),
    ]
