# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0004_auto_20181115_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_contents', models.TextField(default='')),
                ('review_sentiments', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='review_contents',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='review_sentiments',
        ),
    ]
