# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0005_auto_20181116_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
