# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review_data', '0006_auto_20181116_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_contents', models.TextField(default='')),
                ('review_sentiments', models.TextField(default='')),
                ('rmovie_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_data.Movie')),
            ],
        ),
    ]
