# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0007_movie_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rmovie_title',
        ),
    ]
