# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0008_remove_review_rmovie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rmovie_title',
            field=models.IntegerField(default=0),
        ),
    ]
