# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0009_review_rmovie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rmovie_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_data.Movie'),
        ),
    ]
