# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0010_auto_20181116_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rmovie_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='review_data.Movie'),
        ),
    ]
