# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0011_auto_20181120_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rmovie_title',
        ),
        migrations.AddField(
            model_name='review',
            name='movienum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
