# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0012_auto_20181122_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movienum',
        ),
    ]
