# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0014_review_rmovie_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rmovie_num',
        ),
        migrations.AddField(
            model_name='review',
            name='rmovie_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='review_data.Movie'),
            preserve_default=False,
        ),
    ]
