# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0015_auto_20181122_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_contents',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_sentiments',
            new_name='sentiments',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rmovie_title',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review_data.Movie'),
            preserve_default=False,
        ),
    ]
