# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0016_auto_20181122_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_src',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_synp',
            field=models.TextField(default=''),
        ),
    ]
