# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0017_auto_20181126_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_src',
            new_name='src',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_synp',
            new_name='synp',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_no',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_title',
        ),
        migrations.AddField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_data.Movie'),
        ),
    ]
