# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0020_review_figure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='figure',
        ),
    ]
