# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0021_remove_review_figure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sentiments',
        ),
        migrations.AddField(
            model_name='review',
            name='sentiments_comp',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiments_neg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiments_neu',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiments_pos',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
