# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_data', '0022_auto_20181130_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiments',
            field=models.TextField(default=''),
        ),
    ]
